on:
  push:
    branches:
    - fix-git-action

name: Check dist/index.js

jobs:
  build:
    name: npm run build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          npm ci && npm run build
      - name: Check dist/index.js
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
